### ISSUE TITLE
Grid-tables normalization

### ISSUE THREAD

**Issue by donatelloOo** [jterrace/eclipse-resteditor#1]
One of the worst thing of typing documentation in ReST is to normalize grid tables.
Whereas it is said to be supported (as for sections normalization), it does not work.

Example:

+------------------------+------------------------------+
| Pattern       | Entity |
+========================+==============================+
| Test         | value |
+------------------------+------------------------------+

Here, the columns are not strictly aligned, neither on header or body, and this is never normalize (even if the header is correctly defined).

Hope you can provide an quick & easy fix !
Using Eclipse Oxygen / Sphinx 1.7+
By the way, the plugin is very good for everything else !

**Comment by jterrace** [comment]
This is just a github mirror. Please report issues at the root project here:
https://sourceforge.net/p/resteditor/bugs/?source=navbar
